apiVersion: batch/v1
kind: Job
metadata:
  name: cdc-framework-smoke
  labels:
    app: consumer-driven-contract-testing
spec:
  template:
    metadata:
      labels:
        app: consumer-driven-contract-testing
    spec:
      restartPolicy: Never
      containers:
        - name: framework
          image: __IMAGE__
          imagePullPolicy: Always
  backoffLimit: 0
